### ISSUE TITLE
pip version of condor does not run on python 2

### ISSUE THREAD

**Issue by FilipeMaia** [FXIhub/condor#10]
`In [1]: import condor
  File "/Users/filipe/Library/Python/2.7/lib/python/site-packages/condor/task.py", line 55
    def __init__(self, name : str, wdir : str, args : dict, using_pipe : bool = False):
                            ^
SyntaxError: invalid syntax
`

**Comment by mhantke** [comment]
I have not created a pip repository for condor. Sure we are talking about the same condor?

**Comment by FilipeMaia** [comment]
Oops, you're right it's a different condor. 
It would be nice to have condor in pip regardless.

**Comment by mhantke** [comment]
True - I tried once but it turned out complicated because of the nfft dependency...
