### ISSUE TITLE
Syntax change with NFFT 3.3

### ISSUE THREAD

**Issue by daurer** [FXIhub/condor#12]
Since NFFT 3.3, the keyword argument `nfft_flags` of the `fft_plan` module has been renamed to `flags`.  This creates a problem in the following file

https://github.com/FXIhub/condor/blob/150f6806ebea671438a2cc9f995171f84523db03/src/utils/nfft/nfftmodule.c#L69-L72

I tried to fix this by checking for the NFFT version, but I didn't find any working solution so far...

**Comment by mhantke** [comment]
Fixed with 25316d65ddb3c30e43fe89e6b51e20c9d213f9b3
