### ISSUE TITLE
Example PDB file does not match with spsim parsing of atomic number

### ISSUE THREAD

**Issue by daurer** [FXIhub/condor#14]
Since the spsim commit https://github.com/FilipeMaia/spsim/commit/fc920d802799376a47bfd4849a006b2698aa4d48#diff-573b39bd8d69627dd0431d425785abd0L200 columns 77-78 are parsed when searching for the atomic number in the PDB file. These columns don't exist in the example file DNA.pdb which causes the examples to be erratic. 

A quick fix could be to use a complete PDB file instead. Even better would be to make spsim parse the atomic number in both cases (with and without the element columns 77-78), see https://github.com/FilipeMaia/spsim/issues/8

**Comment by mhantke** [comment]
Fixed with 92efad1876084a69c80be7bbecd2575c9ba80fa8.
