### ISSUE TITLE
Is Python 3.9 supported?

### ISSUE THREAD

**Issue by ReMuTh** [FXIhub/condor#35]
Been following installation guides and get
`AttributeError: module 'condor' has no attribute 'main'`
when running `examples.py` 

I'm suspecting this may be due to missing Python 3.9 support?

**Comment by FilipeMaia** [comment]
No, unfortunately we only support up to Python 3.8.

**Comment by FilipeMaia** [comment]
But I think this is actually not a python 3.9 problem.
I just installed condor on a python 3.9 condor environment and was able to run the examples:
```
$ pwd
/Users/filipe/src/condor

$ python --version
Python 3.9.5

$ python examples.py
----------------------------------------------------------------------------------------------------

>>> Example 1/17: PARTICLE IDEAL SPHERE (configfile)
cd /Users/filipe/src/condor/examples/configfile/particle_sphere; rm -f condor.cxi; condor
[start output]
[end output]
>>> Success!

----------------------------------------------------------------------------------------------------
...
```

**Comment by ReMuTh** [comment]
@FilipeMaia Thank you. I agree, not due to 3.9.

Condor actually runs. I tried `import condor`, define detector, source and target and run a simulation literal in a script, that works.
Still puzzled on why the examples fail, tried remowing a reinstialling Condor and all requirement packages, and sort out why a 'main'-attribute is invoked.

**Comment by FilipeMaia** [comment]
If you paste the full traceback it would be easier to figure out the issue.

**Comment by ReMuTh** [comment]
I tried another reinstall, realised a bit of fftw was not properly installed due to permissions.

` /usr/bin/install -c -m 644 FFTW3Config.cmake FFTW3ConfigVersion.cmake '/usr/local/lib/cmake/fftw3'
install: /usr/local/lib/cmake/fftw3/FFTW3Config.cmake: Permission denied
make[2]: *** [install-cmakeDATA] Error 71
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1
`

After sudo `sudo make install` tests now run. Thanks

**Comment by FilipeMaia** [comment]
Glad you figured it out!
