### ISSUE TITLE
Misspelled variable name

### ISSUE THREAD

**Issue by cvazz** [FXIhub/condor#38]
There is a misspelled variable name in condor/particle/particle_sphere.py
On line 103 an L is missing:
    def get_conf(sef): 
rather than
    def get_conf(self):

**Comment by FilipeMaia** [comment]
Thanks!

**Comment by FilipeMaia** [comment]
Fixed by [0506232](https://github.com/FXIhub/condor/commit/05062329e1e54024dd9f0f75407f80730b5ea036).
